import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): import("C:/Users/Administrator/Desktop/nextjs-tsx/node_modules/@types/react/ts5.0/index").JSX.Element {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <header>Wellcome to CRUD Nestjs</header>
          {children}</body>
        <footer>Hop u all fucking well :V</footer>
      </html>
    </>

  )
}
